name: oidc-demo
on:
    push:
        branches:
            - '*'
jobs:
    auth:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - name: Get id token
              env:
                 OIDC_AUDIENCE: 'jfrog-github'
                 OIDC_PROVIDER: 'san-git-intergation'
              run: |
                    ID_TOKEN=$(curl -sLS -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                    "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=${OIDC_AUDIENCE}" | jq .value | tr -d '"')
                    echo "ID_TOKEN=${ID_TOKEN}" >> $GITHUB_ENV
                    echo "$ID_TOKEN"
            - name: Exchange token with access
              env:
                    ID_TOKEN: ${{env.ID_TOKEN}}
                    JFROG_PLATFORM_URL: https://server.jfrog.io
              run: |
                    ACCESS_TOKEN=$(curl -XPOST -H "Content-Type: application/json" "https://incloudmaster.jfrog.io/access/api/v1/oidc/token" -d "{\"grant_type\": \"urn:ietf:params:oauth:grant-type:token-exchange\", \"subject_token_type\":\"urn:ietf:params:oauth:token-type:id_token\", \"subject_token\": \"${ID_TOKEN}\", \"provider_name\": \"san-git-intergation\"}" | jq .access_token | tr -d '"')
                    echo "ACCESS_TOKEN=${ACCESS_TOKEN}" >> $GITHUB_ENV
            - name: list token
              env:
                 OIDC_AUDIENCE: 'jfrog-github'
                 OIDC_PROVIDER: 'san-git-intergation'
                 ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
              run: |
                 docker login incloudmaster.jfrog.io --username shivani --password ${ACCESS_TOKEN}
                 docker pull incloudmaster.jfrog.io/vj-docker-remote/hello-world
